apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: jenkins
    node: master
  name: jenkins
spec:
  replicas: 1
  selector:
    app: jenkins
    deploymentconfig: jenkins
    node: master
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins
        deploymentconfig: jenkins
        node: master
    spec:
      containers:
      - image: jenkins/jenkins:jdk11
        imagePullPolicy: Always
        name: jenkins
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /whoAmI
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 65
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1            
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 50000
          timeoutSeconds: 1            
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-master
      volumes:
      - name: jenkins-master
        persistentVolumeClaim:
          claimName: jenkins-master
  triggers:
  - type: ConfigChange
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-block
    volume.beta.kubernetes.io/storage-provisioner: gluster.org/glusterblock
  name: jenkins-master
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
