apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
    app: jenkins
    name: jnlp-slave
    node: slave
  name: jnlp-slave
spec:
  replicas: 1
  selector:
    app: jenkins
    deploymentconfig: jnlp-slave
    name: jnlp-slave
    node: slave
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins
        deploymentconfig: jnlp-slave
        name: jnlp-slave
        node: slave
    spec:
      containers:
      - command:
        - jenkins-slave
        - -tunnel
        - jenkins:50000
        - maven
        env:
        - name: JENKINS_URL
          value: http://jenkins:8080
        - name: JENKINS_TUNNEL
          value: jenkins:50000
        - name: JENKINS_AGENT_NAME
          value: maven
        - name: JENKINS_AGENT_WORKDIR
          value: /home/jenkins/slave
        image: jenkins/jnlp-slave:latest-jdk11
        imagePullPolicy: IfNotPresent
        name: jnlp-slave
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
        volumeMounts:
        - mountPath: /home/jenkins/.jenkins
          name: jnlp-slave-home
        - mountPath: /home/jenkins
          name: jenkins-slave
      volumes:
      - emptyDir: {}
        name: jnlp-slave-home
      - name: jenkins-slave
        persistentVolumeClaim:
          claimName: jenkins-j11
  - type: ConfigChange
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: gluster-block
    volume.beta.kubernetes.io/storage-provisioner: gluster.org/glusterblock
  name: jenkins-j11
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
