apiVersion: v1
kind: Template
metadata:
  name: ${PROJ_NAME}-build-template
parameters:
  - name: PROJ_NAME
    required: true
  - name: SITE_REPO
    required: true
  - name: REPO_BRANCH
    required: true
objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: ${PROJ_NAME}
    name: ${PROJ_NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${PROJ_NAME}:latest
    source:
      git:
        ref: tools
        uri: ${SITE_REPO}
      type: Git
    resources:
      limits:
        cpu: "1000m"
        memory: "2Gi"
    strategy:
      dockerStrategy:
        env:
        - name: BRANCH
          value: ${REPO_BRANCH}
        - name: REPO
          value: ${SITE_REPO}
        from:
          kind: ImageStreamTag
          name: maven:3-jdk-11
          namespace: 3aa7ll-tools
      type: Docker
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      build: ${PROJ_NAME}
    name: ${PROJ_NAME}
  spec:
    tags:
    - annotations: null
      from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/3aa7ll-tools/${PROJ_NAME}:latest
      name: latest
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      builder: maven-3
      jdk-version: '11'
    name: maven
  spec:
    tags:
    - annotations:
        openshift.io/imported-from: 'maven:3-jdk-11'
      from:
        kind: DockerImage
        name: 'maven:3-jdk-11'
      name: 3-jdk-11
