apiVersion: v1
kind: Template

labels:
  template: router-sidecar-buildconfigs

message: |-
    The following objects have been created in your project:

    ImageStream
    BuildConfig
      ${ROUTE_PLANNER_BUILD_CONFIG_NAME}
      ${ROUTE_CONFIG_ADMIN_BUILD_CONFIG_NAME}

    The resulting BuildConfigs, when run, create an imageStream containing the indicated version of the relevant WAR file.

      * When the associated Deployment runs, this imageStream is used as an initContainer in a pod.
      * It's purpose is to "copy the WAR file e.g. the ols-router-admin.war to /app/ROOT.war"
      * The long-running container then launches tomcat which subsequently loads the WAR, thus starting the application.

    These build configs follows the pattern decribed here:

    https://github.com/kubernetes/examples/tree/master/staging/javaweb-tomcat-sidecar

    For more information about using this template, including OpenShift considerations, please contact teh rocketchat community.
metadata:
  annotations:
    description: |-
      ols-router-sidecar BuildConfig Template for use in OpenShift.

    iconClass: icon-other-unknown
    openshift.io/display-name: ols-router-sidecar
    openshift.io/documentation-url: https://github.com/bcgov/ols-router
    openshift.io/long-description: >-
      This template provides a parameterized BuildConfig for the ols-router-sidecare containers.
      The resulting BuildConfig, when run, created an imageStream containing the indicated version of the ols-router-web WAR file.

        * When the associated Deployment runs, this imageStream is used as an initContainer in a pod.
        * It's purpose is to "copy the ols-router.war to /app/ROOT.war"
        * The long-running container then launches tomcat which subsequently loads the WAR, thus starting the application.

      For details on the patter being used see:
        https://github.com/kubernetes/examples/tree/master/staging/javaweb-tomcat-sidecar
    openshift.io/provider-display-name: DataBC-OLS
    openshift.io/support-url: https://github.com/bcgov/ols-router
    tags: router
  name: ols-router-sidecar-template

parameters:

  - name: ROUTE_PLANNER_IMAGESTREAM_NAME
    description: The name of the Route planner API ImageStream to be created
    displayName: Route Planner API ImageStream Name
    required: true
    value: ols-router-sidecar
  - name: ROUTE_CONFIG_ADMIN_IMAGESTREAM_NAME
    description: The name of the Route Cofing Admin WebApp ImageStream to be created
    displayName: Route Config Admin WebApp ImageStream Name
    required: true
    value: ols-router-admin-sidecar

  - description: The name of the Route planner API Build Config to be created
    displayName: Route Planner API BuildConfig Name
    name: ROUTE_PLANNER_BUILD_CONFIG_NAME
    required: true
    #value: ols-router-sidecar
    value: sidecar-router
  - description: The name of the Config Admin WebApp Build Config to be created
    displayName: Config Admin WebApp BuildConfig Name
    name: ROUTE_CONFIG_ADMIN_BUILD_CONFIG_NAME
    required: true
    value: sidecar-router-admin

objects:

- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    creationTimestamp: null
    labels:
      app: ${ROUTE_PLANNER_BUILD_CONFIG_NAME}
    name: ${ROUTE_PLANNER_BUILD_CONFIG_NAME}
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${ROUTE_PLANNER_IMAGESTREAM_NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      dockerfile: |
        FROM tomcat:9-jdk11-openjdk-slim-bullseye
        RUN mkdir /usr/local/tomcat/webapps/ROOT
        WORKDIR "/usr/local/tomcat/webapps/ROOT"
        COPY router.war /usr/local/tomcat/webapps/ROOT/ROOT.war
        RUN jar -xvf ROOT.war
        WORKDIR "/usr/local/tomcat/"
        RUN mv /usr/local/tomcat/webapps/ROOT/ROOT.war /usr/local/tomcat/webapps/
      type: Dockerfile
    strategy:
      dockerStrategy: {}
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers: []
  status: {}

- kind: BuildConfig
  apiVersion: build.openshift.io/v1
  metadata:
    creationTimestamp: null
    labels:
      app: ${ROUTE_CONFIG_ADMIN_BUILD_CONFIG_NAME}
    name: ${ROUTE_CONFIG_ADMIN_BUILD_CONFIG_NAME}
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: ${ROUTE_CONFIG_ADMIN_IMAGESTREAM_NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      dockerfile: |
        FROM tomcat:9-jdk11-openjdk-slim-bullseye
        RUN mkdir /usr/local/tomcat/webapps/int
        WORKDIR "/usr/local/tomcat/webapps/int"
        COPY ols-admin.war /usr/local/tomcat/webapps/int/int.war
        RUN jar -xvf int.war
        WORKDIR "/usr/local/tomcat/"
        RUN mv /usr/local/tomcat/webapps/int/int.war /usr/local/tomcat/webapps/
        RUN sed -i 's@<Connector @<Connector maxHttpHeaderSize="65536" @g' /usr/local/tomcat/conf/server.xml
      type: Dockerfile
    strategy:
      dockerStrategy: {}
      type: Docker
    successfulBuildsHistoryLimit: 5
    triggers: []
  status: {}
