name: Java CI

on: [push]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java_version: [1.11]
        os: [ubuntu-latest]

    steps:   
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java_version }}
    - name: Build with Maven    
      run: mvn clean package --file pom.xml
      
    steps:   
    - name: Scan with SonarQube
      env: 
        SONAR_URL: ${{ secrets.SONAR_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    
      run: mvn sonar:sonar -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_TOKEN --file pom.xml
