name: Java CI

on: [push]

jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java_version: [1.11]
        os: [ubuntu-latest]
        mvn_ver: [2.0.0]

    steps:   
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java_version }}
    - name: Update Maven Release Version
      run: mvn versions:set -DnewVersion='${{ matrix.mvn_ver }}' -DgenerateBackupPoms=false --file pom.xml
    - name: Build with Maven and Scan with SonarCloud
      env: 
        SONAR_URL: ${{ secrets.SONAR_CLOUD_URL }}
        SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}    
      run: mvn clean package org.sonarsource.scanner.maven:sonar -Dsonar.host.url=$SONAR_CLOUD_URL -Dsonar.login=$SONAR_CLOUD_TOKEN --file pom.xml
